# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- task: AzureStaticWebApp@0
  displayName: 'Deploy'
  inputs:
    app_location: '$(projectSrcPath)/dist'
    output_location: '/src'
    azure_static_web_apps_api_token: 28d52a2b480ed1f0a9fdf7f73ef5097b7fd4591e117dd56402fa6a4a918558c01-209e9b7b-d684-4395-9f45-245c4416baa301077804
    skip_app_build: true
    verbose: true
